services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "90:80"
    depends_on:
      - flask
    networks:
      - app-network

  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge